apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbyee
spec:
  params:
  - name: username
    type: string

  steps:
    - name: goodbyee
      image: ubuntu
      script:
        #!/bin/bash
        echo "Goodbye $(params.username)!"   